(source melpa)

(depends-on "zenburn-theme")
(depends-on "coffee-mode")
(depends-on "ag")
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "less-css-mode")
(depends-on "yaml-mode")
